const CurrencyList : Currency[] = [
  { code: "USD", name: "United States Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound Sterling", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" }, 
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  {code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  {code: "PHP", name: "Philippine Peso", symbol: "₱" },
  {code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  {code: "THB", name: "Thai Baht", symbol: "฿" },
  {code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },

]

export default CurrencyList;